Blog/formula fields before context
Duelfer-Solutions/sfdx-developer pull request #12
Opened 2023-05-08 19:37 UTC by tamarachance

## Overview:

This branch contains the full blog post for working with formula fields in the before context of apex triggers. I used the "Blog" category when creating the branch to avoid any confusion with future website "Feature" branches. 

The blog post details the specific problem and limitation of formula fields that rely on data that has been committed to the database. The post provides an anonymized version of the problem and outlines the code that caused the problem, the test class that caught the problem, and then the solution code for manually breaking down the formulas. 

There are three images added into the text and a link at the end to a gist containing all of the files mentioned in the post.
 - OpportunityTriggerHandler
 - ProposalTriggerHandler
 - CalculateValues
 - CalculateValues_Test
 
Gist: https://gist.github.com/tamarachance/e44db2f1ffcc04e1a47a10507d0f1f9b

## Special Considerations:
- The datetime on the blog will need to be updated before publishing or in the future we can utilize a drafts folder.
- I chose to create a file structure for organizing images that were specific to the post. This was mostly for clarity, but also in case we ever wanted to add featured images for each post. There are only 4 other blog posts so I can recreate the file structure for the other 4 posts or remove it if it isn't helpful.
- Before being able to run the `jekyll serve` command, I had to run `bundle add webrick`. This updated my gem file and gem lock file to include webrick. I did not commit that change, though, since it was only necessary for my version of bundler.

2023-07-05 11:48 UTC, jduelfer requested changes
Awesome! Getting really close to getting this out - I left a number of comments on trying to make the problem and solution more clear, and a couple code-style updates. Overall, I think it's really good and expect this to be the last round of changes.

Make sure to update your Github gist with any code changes (it's probably best to update your gist and copy and past into the blog post, but up to you).

2023-07-05 11:48 UTC, jduelfer commented on _posts/2023-05-08-formula-fields-before-context.markdown
> +Let's say that a retail business needs to populate a `Total_Value__c` field on each Opportunity based on a calculation that adds together the values from three other fields also on the Opportunity ob
Really good example, but I'd say it's overly complex. I'd bake it down to something like the following:

> Let's say that a retail business has a custom field on the Opportunity object called `Total_Value__c` that's quite complex and requires Apex code to calculate. Their developers have written this calculation in the Opportunity before trigger, pulling together a number of fields from the Opportunity object and a related object `Proposal__c`.

> As good developers, they needed to support a couple formula fields that the company's admins put together. So their calculation used both standard input fields _and_ formula fields. They abstracted these calculations into a utility class, called `CalculateValues` which is called from the Opportunity trigger and looks something like the following:

2023-07-05 11:48 UTC, jduelfer commented on _posts/2023-05-08-formula-fields-before-context.markdown
> +    public static void setProposalData(OpportunityTriggerHandler.OpportunityContext ctx) {
Let's remove the `OpportunityTriggerHandler.OpportunityContext ctx` param and replace it simply with the `Opportunity` and `Proposal__c`. For example, your method signatures should look like the following:

`setProposalData(Opportunity opp, Proposal__c proposal)`
`setDataFromProposal(Opportunity opp, Proposal__c proposal)`

2023-07-05 11:48 UTC, jduelfer commented on _posts/2023-05-08-formula-fields-before-context.markdown
> +        setDataFromProposal(ctx); //Fields are mapped here, then
No need for the inline comment here or the next line, the function should have a codeblock comment.

2023-07-05 11:48 UTC, jduelfer commented on _posts/2023-05-08-formula-fields-before-context.markdown
> +/*
Code block comments have the following format
```
/**
 * Description of class...
 */
```
The two asterisks are important for the code block structure, as well as the indentation. Lots of tools (like VS code) use this syntax to auto-load documentation and help pop-ups.

2023-07-05 11:48 UTC, jduelfer commented on _posts/2023-05-08-formula-fields-before-context.markdown
> +
Functions should not have a space on the first line - code should immediately begin.

2023-07-05 11:48 UTC, jduelfer commented on _posts/2023-05-08-formula-fields-before-context.markdown
> +    public static void setTotalValueMetric(OpportunityTriggerHandler.OpportunityContext ctx) {
No need to have a one-line function like this. Just put this line up in the `setProposalData` function for readability. So it would look like:
```
public static void setProposalData(Opportunity opp, Proposal__c proposal) {
    setDataFromProposal(opp, proposal);
    opp.Total_Value__c = calculateTotalValue(opp);
}
```

2023-07-05 11:48 UTC, jduelfer commented on _posts/2023-05-08-formula-fields-before-context.markdown
> +
Before jumping in, I would add something like the following:

> Now comes the kicker: the `Total_Order__c` and `Total_Transportation_Cost__c` fields used in the `calculateTotalValue` function are both formula fields. Here's a screenshot of the formula next to where they are referenced in the code:

I'd remove the other two paragraphs: whenever a proposal... and then, the context...

I think they get a bit too far into the weeds.

2023-07-05 11:48 UTC, jduelfer commented on _posts/2023-05-08-formula-fields-before-context.markdown
> +…the assertion fails. So what’s the problem?
Nice! Would you consider adding a subsection after this line? I like the suspense, might be worth breaking it up.

2023-07-05 11:48 UTC, jduelfer commented on _posts/2023-05-08-formula-fields-before-context.markdown
> +This trigger calls another class that contains the logic to overwrite the three field values on the Opportunity based on data from a related proposal. Here’s an example of what the class in our ficit
I think these two paragraphs can be removed, as we cover this in the above, updated example.

2023-07-05 11:48 UTC, jduelfer commented on _posts/2023-05-08-formula-fields-before-context.markdown
> +Here’s an example test class for this calculation that asserts what you might expect the results for the Total_Value__c fields to be based on the above code:
Make sure to add any fields, like `Total_Value__c` inside the code formatting ("` `")

2023-07-05 11:48 UTC, jduelfer commented on _posts/2023-05-08-formula-fields-before-context.markdown
> +The newly mapped opportunity fields are required as inputs to the formula fields being used in the calculateTotalValue calculation.
Let's remove this line.

2023-07-05 11:48 UTC, jduelfer commented on _posts/2023-05-08-formula-fields-before-context.markdown
> +The formula fields for Total_Order__c and Total_Transportation_Cost__c ran when the trigger was first called. Before the mapping occurred and was committed to the database.
Really good characterization. I would update just to be a little more specific:

> The formula fields for `Total_Order__c` and `Total_Transportation_Cost__c` ran when the trigger was first called. Uploading the proposal, however, affects the resulting value of these fields. Formula fields rely on data that has already been committed to the database, and because the changes made by the uploaded proposal are _not yet committed to the database_, the values that Salesforce loads for `Total_Order__c` and `Total_Transportation_Cost__c` are incorrect. 

> After update, if you were to run the calculation again with no additional changes made to the underlying fields, the formula fields would reflect correct values and the Total Value calculation would be as expected. This is because the after trigger occurs after database commit and reloads any formula field values.

2023-07-05 11:48 UTC, jduelfer commented on _posts/2023-05-08-formula-fields-before-context.markdown
> +- Make sure to perform testing to ensure your calculations are accurate and don't rely on any incorrect data.
I'd say "incorrect or stale data"

2023-07-05 11:48 UTC, jduelfer commented on _posts/2023-05-08-formula-fields-before-context.markdown
> +
Here, I'd add a brief statement that there is a limitation to your solution - it forces you to _replicate_ the formula field in Apex. So you would have to be aware of any changes to this field and synchronize them with changes to the underlying code. This adds overhead, but it might be a necessary trade-off.

2023-07-05 11:48 UTC, jduelfer commented on _posts/2023-05-08-formula-fields-before-context.markdown
> +}
As part of code style and best practices, make sure indentation is consistent. You should following these guidelines:

- `if (` should have a space between if and the parenthesis
- `) {` the parenthesis and the bracket should have a space between them.
- `} else {` brackets should always have a space before or after them
- parentheses should always have a space after them, and generally before them, _except_ in method signatures `calculateTotalValue(` does not have a space before the paren.

2023-07-26 21:46 UTC, tamarachance commented on _posts/2023-05-08-formula-fields-before-context.markdown
> +…the assertion fails. So what’s the problem?
For the sake of getting this one out the door, I decided not to add anything extra.

2023-08-02 09:39 UTC, merged