Blog/updating the blog design
Duelfer-Solutions/sfdx-developer pull request #13
Opened 2023-09-11 15:09 UTC by tamarachance

# Overview

Alters the design of the website to modernize the theme and adds some co-branding:

- The header matches the color of the Duelfer Solutions brand.
- The home page blog feed shows a list of blog cards that includes a featured image, the blog title, and a brief excerpt.
- The post pages contain featured images at the top of the blog
- The about page has been updated to reflect more of a community blog space rather than a portfolio blog and Jon's old profile photo was removed and replaced with the SFDX Developer logo image instead. And a link to Duelfer Solutions website was added in the text. 
- The images for individual post have been filed so that it is easier to locate images and it provides a structure for future posts.
- A stock image library folder has been added to the asset tree for scalability. As more posts are added, featured images can be pulled from this stock image library. 
- The config file has been updated to include excerpts, but only the first sentence.

## Special Considerations

- When adding new posts, pull stock images and add them to the stock image folder.
- Add post images into unique post image folder
- The excerpts break on the first sentence, so if the first sentence of a post is short the excerpt will look oddly short. Ensure that the excerpt is showing as expected.

## Release Notes

> - Added a stock image folder for featured images as the blog scales
> - Added featured images to all blog posts
> - Added blog card layout to the home feed
> - Updated the About page with new image and new text

2023-09-14 09:48 UTC, jduelfer requested changes
Love the upgrade already!! Branding, texts, images, it also is a great step forward.

I'm also a fan of canva - let's move forward with it, but let's do monthly instead of yearly since we will want to upgrade to team most likely and don't want to get locked into anything! If you want to cancel your free trial, I'm happy to set one up for us!

Only thing that jumped out at me that needs to be updated are the images on the home page. They are showing up "squished" on my screen (not sure if this happens on all screen sizes). I believe this is because the image is being converted to a square instead of its rectangular original image (which looks great on the blog post headers).
![image](https://github.com/Duelfer-Solutions/sfdx-developer/assets/11039018/262fb724-8942-4b62-957f-52804f1e287a)


This also appears to happen for mobile.
![image](https://github.com/Duelfer-Solutions/sfdx-developer/assets/11039018/b5e444be-49bf-4151-9914-9c9dc6b8ad5a)

2023-09-14 09:48 UTC, jduelfer commented on assets/css/style.css
> +  .card-featured-image {
I believe this is the culprit for the "squished" images. You might need to experiment with the scale a little, or potentially "cropping" the image to get a square via css.

Alternatively, a completely reasonable quick solution could be to upload a thumbnail image for each blog post as well, which is cropped to a square manually via paint or something. Completely up to you though!

2023-09-14 09:48 UTC, jduelfer commented on assets/img/profile.jpeg
YES THANK YOU FOR DELETING LOL

2023-09-14 09:48 UTC, jduelfer commented on about.md
> +Welcome to the SFDX Developer Blog. Written by developers and for developers, we're excited to contribute to the Salesforce Developer Ohana.
Really like this upgrade!!

2023-09-14 09:48 UTC, jduelfer commented on about.md
> +SFDX Developer is a dedicated platform for discussing Salesforce Development tips & tricks hosted by [Duelfer Solutions, L.L.C.](https://duelfersolutions.com/) We understand the unique challenges fac
Also super well written, thanks for pulling this together!!

2023-09-14 09:48 UTC, jduelfer commented on assets/css/style.css
> +.feed .post-card {
I think you might need to review this css class a little to make sure that the home page appears well on mobile. Doesn't need to be super fancy (it was very _not_ fancy before), but I'd say it should at least have a little spacing between each card.

2023-09-21 19:25 UTC, tamarachance commented on assets/css/style.css
> +  .card-featured-image {
It was because I have the `object-fit: fill;` set on the cards. This is so that rectangular images will fill the 150x150 area. I experimented with changing this property but it makes the other images look worse. In the end, I just got a new image to use as the default. I added a note to the special considerations to make sure that any images selected will look nice in both settings.

2023-09-21 19:28 UTC, tamarachance commented on assets/css/style.css
> +.feed .post-card {
I added a media query to alter the layout when screen size drops below 720 width.

2023-09-21 20:52 UTC, tamarachance commented on assets/css/style.css
> +  .card-featured-image {
Instead of `object-fit: fill;`, I've changed it to `object-fit: cover;` but it meant changing out the images to better images that won't mess up when zoomed in. I added a note to the special considerations regarding image selection for future use.

2023-10-03 10:44 UTC, jduelfer commented on assets/css/style.css
> +  .card-featured-image {
Sounds like a solid solution and looks good!

2023-10-03 10:44 UTC, jduelfer commented on assets/css/style.css
> +.feed .post-card {
Great solution - media queries are life-savers.

2023-10-03 10:48 UTC, jduelfer approved these changes
Looks awesome! Great redesign and I'm really liking the home page update.

I'm going ahead and approving this PR (and having Github push to prod automatically), but there are a couple updates I think we can make in the long-term that are beyond this PR (your work has already made big strides forwards).

1. On mobile, the _Home_ page, I think, would be easier to read if the image was on top of the text and the text (title and description) took up the width of the page. 
![image](https://github.com/Duelfer-Solutions/sfdx-developer/assets/11039018/f84196d0-723d-43f5-b8a9-d1470daf91bc)
2. The _About_ page's image is positioned a little weird on mobile. It'd be nice for the image to be centered under a certain pixel width.
![image](https://github.com/Duelfer-Solutions/sfdx-developer/assets/11039018/873ec24e-916b-447a-8878-5d3318308dae)

Going to add these to a separate Jira card - might be a great task for a new member onboarding to work with this minor CSS tweaks!

2023-10-03 10:49 UTC, merged